spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
        url: jdbc:mysql://stackoverflow-005.cgbzoy0x62zh.ap-northeast-2.rds.amazonaws.com/stackoverflow005?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
        username: admin
        password:  ${MYSQL_SECRET}
        driver-class-name: com.mysql.cj.jdbc.Driver



jwt:
  secretKey: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

